services:
  postgres:
    image: postgres:16.2
    restart: always
    tty: true
    ports:
      # Accessible from the host at port :15432
      - "15432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
