name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Run tests
        run: yarn test

      - name: Build app
        run: yarn build

      # - name: Configure AWS Credentials
      #   if: ${{ github.repository == 'swan-io/url-shortener' }}
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE }}
      #     aws-region: eu-west-1

      # - name: Login to Docker Registry
      #   if: ${{ github.repository == 'swan-io/url-shortener' }}
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ secrets.DOCKER_REGISTRY }}

      # - name: Dockerize & Push to Registry
      #   if: ${{ github.repository == 'swan-io/url-shortener' }}
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKER_REGISTRY }}/url-shortener:master-${{ github.sha }}
      #       ${{ secrets.DOCKER_REGISTRY }}/url-shortener:master-${{ github.ref_name }}

      # - name: Deploy
      #   if: ${{ github.repository == 'swan-io/url-shortener' }}
      #   run: yarn deploy-ci
      #   env:
      #     TAG: master-${{ github.sha }}
      #     DEPLOY_SWAN_TOKEN: ${{ secrets.DEPLOY_SWAN_TOKEN }}
      #     DEPLOY_SWAN_REPOSITORY: ${{ secrets.DEPLOY_SWAN_REPOSITORY }}
      #     DEPLOY_GIT_USER: ${{ secrets.DEPLOY_GIT_USER }}
      #     DEPLOY_GIT_EMAIL: ${{ secrets.DEPLOY_GIT_EMAIL }}
      #     DEPLOY_ENVIRONMENT: master
      #     DEPLOY_APP_NAME: url-shortener
