name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build app
        run: pnpm build

      - name: Configure AWS Credentials
        if: ${{ github.repository == 'swan-io/url-shortener' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-1

      - name: Login to Docker Registry
        if: ${{ github.repository == 'swan-io/url-shortener' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}

      - name: Dockerize & Push to Registry
        if: ${{ github.repository == 'swan-io/url-shortener' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/url-shortener:master-${{ github.sha }}
            ${{ secrets.DOCKER_REGISTRY }}/url-shortener:master-${{ github.ref_name }}

      - name: Deploy
        if: ${{ github.repository == 'swan-io/url-shortener' }}
        run: pnpm deploy-ci
        env:
          TAG: master-${{ github.sha }}
          DEPLOY_SWAN_APP_ID: ${{ secrets.DEPLOY_SWAN_APP_ID }}
          DEPLOY_SWAN_APP_SECRET: ${{ secrets.DEPLOY_SWAN_APP_SECRET }}
          DEPLOY_ENVIRONMENT: master
          DEPLOY_APP_NAME: url-shortener
